DARPA-ASKEM/knowledge-middleware

- workers/Dockerfile
- workers/operations.py
- workers/utils.py
- MathML to AMR works
- publication extraction is able to get the extractions back from the lum.ai hosted instance, but not able to update the artifact in TDS
- data profiling does not work yet, the payload we get back is not what we've been expecting
- linking is untested
> fix docker build and improve logging

- api/server.py
- workers/operations.py
- workers/utils.py
Splits PDF to text and PDF extraction into 2 endpoints.
Not able to test PDF extraction currently since there is a bug on the TA1 side but this _should_ work. Famous last words....
> Added support for pdf extraction + pdf to text

- api/Dockerfile
- api/server.py
- workers/operations.py
- workers/utils.py
* Better logging for code 2 AMR 
* tested code 2 AMR
* improved code 2 amr and equation 2 amr endpoints to allow name/description specification
* added support for latex and added parameter to specify `equation_type`: `[latex, mathml]`
* cleaned up server dockerfile
> Code2AMR++

- .github/workflows/pytest_workflow.yml
- .pre-commit-config.yaml
- docker-compose.prod.yaml
- docker-compose.yaml
- poetry.lock
- pyproject.toml
Simple YAML linting fixes to ensure build works
> fix linting issues

- pyproject.toml
- tests/test_e2e.py
This PR 
1. Does not create an AMR if jobs failed
2. Write traceback of job error
> Add traceback info

- tests/scenarios/sidarthe/config.yaml
- tests/scenarios/sidarthe/equations.txt
This runs the equations to AMR test based on the laTex that @Free-Quarks provided!
> add equations for SIDARTHE and set up eqn to amr test for that scenario

- tests/test_e2e.py
> add quality checks for pdf extraction

- worker/operations.py
Based on the following bug:
```log
18:09:51 default: worker.operations.data_card(dataset_id='48d32258-83ac-476a-a27b-5d028e39357c', document_id=None, job_id='extraction-8b1b7aae-1d2a-46b0-87fd-dd60ac685630') (extraction-8b1b7aae-1d2a-46b0-87fd-dd60ac685630)
2023-10-10 18:09:52,082 - worker.utils - INFO - [242] - DATASET RESPONSE JSON: {'id': '48d32258-83ac-476a-a27b-5d028e39357c', 'timestamp': '2023-10-05T17:48:21', 'username': 'Emperor Adam', 'name': 'data', 'description': 'data.csv', 'data_source_date': None, 'file_names': ['data.csv'], 'dataset_url': None, 'columns': [{'name': 'date', 'data_type': 'unknown', 'description': None, 'format_str': None, 'annotations': [], 'metadata': None, 'grounding': None}, {'name': 'I', 'data_type': 'unknown', 'description': None, 'format_str': None, …
```
> fix: update data card assignements

- worker/operations.py
> ensure assets propagate on a document

- api/server.py
- worker/operations.py
> Update cosmos call to allow `force_run` parameter

- .github/workflows/report.yaml
> Fix report

- .github/workflows/report.yaml
When a change is made to main, `km/reporting` executes.
> Trigger report on push to main

- reporting/docker-compose.yaml
- reporting/tests/report.py
Fixes env in compose for report generation and strips out openai key from error logs
> Reporting fixes

- reporting/tests/report.py
Conditionally checks whether a reporting task succeeded, failed, was N/A or had an upstream failure.
> Handle report upstream fails

- reporting/tests/report.py
* Cosmos accuracy try catch
* new shape in report.py
Resolves #(issue)
> Catching errors in Cosmos accuracy, changed shape of reporting pipeline.

- .github/workflows/publish.yaml
- .github/workflows/report.yaml
This PR avoids dispatching directly after push to main
> Report after build

- reporting/tests/report.py
* Changes the profile model url based on the existence of a document in the scenario.
> Added conditional to construct profile_model endpoint.

- README.md
- reporting/scenarios/Penn CHIME/repo_url.txt
- reporting/tests/seed.py
- worker/operations.py
- worker/utils.py
* Adds support for repo_url.txt files to define code to be processed in scenarios.
* Updates top level README for reporting test harness. 
Resolves #107 
Resolves #112
> 107 repo urls in scenarios & 112 top level documentation

- worker/operations.py
> Set extraction service response status code to None if it wasn't invoked

- reporting/tests/report.py
Hotfix for report runner's equations to AMR KM integration
> Bugfix in equations to amr reporting

- reporting/tests/report.py
- reporting/tests/seed.py
> Replace reporting id whitespace with dashes

- worker/utils.py
Addresses a bug...I created...where if a model id is specified but the model doesn't exist, no model would be created. It should be happy now :)
> Hotfix for model creation utility logic

- worker/operations.py
> Retain model card during AMR linking
